const SET_ALL_RECIPES = 'SET_ALL_RECIPES';
const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
const REMOVE_ALL_RECIPES = 'REMOVE_ALL_RECIPES';
const ADD_RECIPE = 'ADD_RECIPE';
const UPSERT_RECIPE = 'UPSERT_RECIPE';
const LIKE_UNLIKE_RECIPE = 'LIKE_UNLIKE_RECIPE';
const COMMENT_ON_RECIPE = 'COMMENT_ON_RECIPE';
const DELETE_RECIPE = 'DELETE_RECIPE';

export {
    SET_ALL_RECIPES,
    FETCH_ALL_RECIPES,
    REMOVE_ALL_RECIPES,
    ADD_RECIPE,
    UPSERT_RECIPE,
    LIKE_UNLIKE_RECIPE,
    COMMENT_ON_RECIPE,
    DELETE_RECIPE
};